### ISSUE TITLE
Pagination resetting back to first page

### ISSUE THREAD

**Issue by yvhr** [fiery-data/fiery-data#17]
If you have a collection with more than 2 pages. Invoking `prev()` on the last page always reset back to the first page. Logging `index` reports the proper appropriate index though, it's really the data that was being fetched is the incorrect one.

Been struggling with this issue for quite a while now.

**Comment by ClickerMonkey** [comment]
For now I'm going to have to add a queryReversed option that will be required for `prev`. The firestore API is not set in stone, so dynamically reversing a query is not an option at the moment... so the user will have to provide it.
